// /!\ Part of this has been generated by AI !

import fs from 'fs/promises';
import path from 'path';
import ffmpeg from 'fluent-ffmpeg';

export type VideoCodec = 'h264' | 'h265' | 'av1' | 'vp9' | 'mpeg4' | 'unknown';

export interface VideoMetadata {
    width: number;
    height: number;
    durationSec: number;
    bitrate: number;
    fps: number;
}

export interface VideoFile {
    filePath: string;
    fileName: string;
    sizeBytes: number;
    container: string;
    codec: VideoCodec;
    metadata: VideoMetadata;
    rawCodecString: string;
}

const VIDEO_EXTENSIONS = new Set(['.mp4', '.mkv', '.avi', '.mov', '.webm', '.flv', '.m4v']);

function normalizeCodecName(rawCodec: string): VideoCodec {
    const clean = rawCodec.toLowerCase().trim();
    
    if (clean === 'hevc' || clean === 'h265') return 'h265';
    if (clean === 'h264' || clean === 'avc1') return 'h264';
    if (clean === 'vp9') return 'vp9';
    if (clean === 'av1') return 'av1';
    if (['mpeg4', 'fmp4'].includes(clean)) return 'mpeg4';
    
    return 'unknown';
}

function probeFile(filePath: string): Promise<ffmpeg.FfprobeData> {
    return new Promise((resolve, reject) => {
        ffmpeg.ffprobe(filePath, (err, data) => {
            if (err) return reject(err);
            resolve(data);
        });
    });
}

async function analyzeVideoFile(filePath: string): Promise<VideoFile | null> {
    try {
        const stats = await fs.stat(filePath);
        const data = await probeFile(filePath);

        const videoStream = data.streams.find(s => s.codec_type === 'video');

        if (!videoStream) {
            console.warn(`Didn't find a video stream in : ${filePath}`);
            return null;
        }

        const rawCodec = videoStream.codec_name || 'unknown';
        
        const fpsParts = (videoStream.r_frame_rate || '0/1').split('/');
        const fps = fpsParts.length === 2 ? parseInt(fpsParts[0]) / parseInt(fpsParts[1]) : 0;

        return {
            filePath,
            fileName: path.basename(filePath),
            sizeBytes: stats.size,
            container: path.extname(filePath).replace('.', '').toLowerCase(),
            codec: normalizeCodecName(rawCodec),
            rawCodecString: rawCodec,
            metadata: {
                width: videoStream.width || 0,
                height: videoStream.height || 0,
                durationSec: parseFloat(data.format.duration?.toString() || '0'),
                bitrate: parseInt(data.format.bit_rate?.toString() || '0'),
                fps: Math.round(fps * 100) / 100
            }
        };

    } catch (error) {
        console.error(`Error analyzing file ${filePath}:`, error);
        return null;
    }
}

async function scanDirectory(dirPath: string): Promise<string[]> {
    let files: string[] = [];
    
    try {
        const items = await fs.readdir(dirPath, { withFileTypes: true });

        for (const item of items) {
            const fullPath = path.join(dirPath, item.name);

            if (item.isDirectory()) {
                const subFiles = await scanDirectory(fullPath);
                files = files.concat(subFiles);
            } else if (item.isFile()) {
                const ext = path.extname(item.name).toLowerCase();
                if (VIDEO_EXTENSIONS.has(ext)) {
                    files.push(fullPath);
                }
            }
        }
    } catch (err) {
        console.error(`Error accessing folder ${dirPath}:`, err);
    }

    return files;
}

export async function generateVideoLibrary(rootPaths: string[]): Promise<VideoFile[]> {
    console.log('Starting scan');
    
    const allPaths: string[] = [];
    for (const rootPath of rootPaths) {
        const paths = await scanDirectory(rootPath);
        allPaths.push(...paths);
    }

    console.log(`Found ${allPaths.length} potential video files`);

    const promises = allPaths.map(p => analyzeVideoFile(p));
    const results = await Promise.all(promises);

    const validVideos = results.filter((v): v is VideoFile => v !== null);

    console.log(`✅ ${validVideos.length} videos found.`);
    return validVideos;
}
